apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-sqs-trigger-auth-aws-credentials
  namespace: sales-events-consumer-ns
spec:
  podIdentity:
    provider: aws-eks
---
apiVersion: keda.sh/v1alpha1 # https://keda.sh/docs/2.0/concepts/scaling-deployments/
kind: ScaledObject
metadata:
  name: sales-events-consumer-scaler-02
  namespace: sales-events-consumer-ns
  labels:
    app: sales-events-consumer
    deploymentName: sales-events-consumer
spec:
  scaleTargetRef:
    kind: Deployment
    name: sales-events-consumer
  minReplicaCount: 1    # Change to define how many minimum replicas you want
  maxReplicaCount: 50
  pollingInterval: 30   # Optional. Default: 30 seconds
  cooldownPeriod:  500  # Optional. Default: 300 seconds
  triggers:
  - type: aws-sqs-queue
    authenticationRef:
      name: keda-sqs-trigger-auth-aws-credentials
    metadata:
      queueURL: https://sqs.us-east-2.amazonaws.com/111122223333/reliable_message_q
      queueLength: "2000"
      awsRegion: "us-east-2"
      identityOwner: operator
---
