apiVersion: batch/v1
kind: CronJob
metadata:
  generateName: sales-event-producer-cron-
  labels:
    jobgroup: sales-event-producer-group
spec:
  schedule: "*/1 * * * *"
  parallelism: 2
  backoffLimit: 2
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: sales-event-producer-cron
              image: 'python:3.8.10-alpine'
              command:
                - sh
                - '-c'
              args:
                - wget https://raw.githubusercontent.com/miztiik/event-processor-on-eks/master/stacks/back_end/eks_s3_producer_stack/lambda_src/stream_data_producer.py;pip3 install --user boto3;python3 stream_data_producer.py;
              env:
                - name: STORE_EVENTS_BKT
                  value: sales-events-bkt-stack-databucketd8691f4e-uaxjd1d2l831
                - name: S3_PREFIX
                  value: sales_events
          restartPolicy: OnFailure
  backoffLimit: 4